#
spring.application.name=ishtech-springboot-oms

## DB

## Flyway
spring.flyway.enabled=false
spring.flyway.encoding=UTF-8
spring.flyway.out-of-order=false

## JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

## Log
logging.level.:INFO
logging.level.fi.ishtech=INFO
